### ISSUE TITLE
Description <head> Tag

### ISSUE THREAD

**Issue by jensbambauer** [jensbambauer/gb#8]
Brauchen hauptsächlich für google eine description. Ca 250 Zeichen ist glaube ich der Standard.

**Comment by frontendrob** [comment]
The official online store of Geebird&Bamby™, the creative venture of the German artists Robert G. Achtel and Jens Bambauer. Limited editions of their fine art photography series "The New World" (2012) and "Mart" (2017) are available for worldwide shipping.

**Comment by jensbambauer** [comment]
slightly too long
 "The New World"...

**Comment by frontendrob** [comment]
The official online store of Geebird&Bamby™, the creative venture of the German artists Robert G. Achtel and Jens Bambauer. Worldwide shipping on all pieces.

**Comment by frontendrob** [comment]
Online store of Geebird&Bamby™, creators of the fine art photography series "The New World" (2012) and "Mart" (2017). All pieces shipping worldwide from their studio in Wiesbaden, Germany.

**Comment by frontendrob** [comment]
Immer noch zu lang?

**Comment by frontendrob** [comment]
Title:

Geebird&Bamby™ | Online Store
